export const COUNTRIES = [
    { code: 'BR', label: 'Brasil', ddi: '+55', flag: '🇧🇷' },
    { code: 'US', label: 'Estados Unidos', ddi: '+1', flag: '🇺🇸' },
    { code: 'PT', label: 'Portugal', ddi: '+351', flag: '🇵🇹' },
    { code: 'AR', label: 'Argentina', ddi: '+54', flag: '🇦🇷' },
    { code: 'GB', label: 'Reino Unido', ddi: '+44', flag: '🇬🇧' },
    { code: 'FR', label: 'França', ddi: '+33', flag: '🇫🇷' },
    { code: 'DE', label: 'Alemanha', ddi: '+49', flag: '🇩🇪' },
    { code: 'ES', label: 'Espanha', ddi: '+34', flag: '🇪🇸' },
    { code: 'IT', label: 'Itália', ddi: '+39', flag: '🇮🇹' },
    { code: 'CA', label: 'Canadá', ddi: '+1', flag: '🇨🇦' },
    { code: 'AU', label: 'Austrália', ddi: '+61', flag: '🇦🇺' },
    { code: 'JP', label: 'Japão', ddi: '+81', flag: '🇯🇵' },
    { code: 'CN', label: 'China', ddi: '+86', flag: '🇨🇳' },
    { code: 'IN', label: 'Índia', ddi: '+91', flag: '🇮🇳' },
    { code: 'RU', label: 'Rússia', ddi: '+7', flag: '🇷🇺' },
    { code: 'UY', label: 'Uruguai', ddi: '+598', flag: '🇺🇾' },
    { code: 'CL', label: 'Chile', ddi: '+56', flag: '🇨🇱' },
    { code: 'CO', label: 'Colômbia', ddi: '+57', flag: '🇨🇴' },
    { code: 'PE', label: 'Peru', ddi: '+51', flag: '🇵🇪' },
    { code: 'MX', label: 'México', ddi: '+52', flag: '🇲🇽' },
    { code: 'CH', label: 'Suíça', ddi: '+41', flag: '🇨🇭' },
    { code: 'ZA', label: 'África do Sul', ddi: '+27', flag: '🇿🇦' },
    { code: 'KR', label: 'Coreia do Sul', ddi: '+82', flag: '🇰🇷' },
    { code: 'SA', label: 'Arábia Saudita', ddi: '+966', flag: '🇸🇦' },
    { code: 'AE', label: 'Emirados Árabes', ddi: '+971', flag: '🇦🇪' },
    { code: 'DK', label: 'Dinamarca', ddi: '+45', flag: '🇩🇰' },
    { code: 'SE', label: 'Suécia', ddi: '+46', flag: '🇸🇪' },
    { code: 'NO', label: 'Noruega', ddi: '+47', flag: '🇳🇴' },
    { code: 'FI', label: 'Finlândia', ddi: '+358', flag: '🇫🇮' },
    { code: 'NL', label: 'Holanda', ddi: '+31', flag: '🇳🇱' },
    { code: 'BE', label: 'Bélgica', ddi: '+32', flag: '🇧🇪' },
    { code: 'AT', label: 'Áustria', ddi: '+43', flag: '🇦🇹' },
    { code: 'PL', label: 'Polônia', ddi: '+48', flag: '🇵🇱' },
    { code: 'IE', label: 'Irlanda', ddi: '+353', flag: '🇮🇪' },
    { code: 'NZ', label: 'Nova Zelândia', ddi: '+64', flag: '🇳🇿' },
    { code: 'TR', label: 'Turquia', ddi: '+90', flag: '🇹🇷' },
    { code: 'IL', label: 'Israel', ddi: '+972', flag: '🇮🇱' },
    { code: 'GR', label: 'Grécia', ddi: '+30', flag: '🇬🇷' },
    { code: 'CZ', label: 'República Checa', ddi: '+420', flag: '🇨🇿' },
    { code: 'HU', label: 'Hungria', ddi: '+36', flag: '🇭🇺' },
    { code: 'RO', label: 'Romênia', ddi: '+40', flag: '🇷🇴' },
    { code: 'TH', label: 'Tailândia', ddi: '+66', flag: '🇹🇭' },
    { code: 'VN', label: 'Vietnã', ddi: '+84', flag: '🇻🇳' },
    { code: 'ID', label: 'Indonésia', ddi: '+62', flag: '🇮🇩' },
    { code: 'MY', label: 'Malásia', ddi: '+60', flag: '🇲🇾' },
    { code: 'SG', label: 'Cingapura', ddi: '+65', flag: '🇸🇬' },
    { code: 'PH', label: 'Filipinas', ddi: '+63', flag: '🇵🇭' },
    { code: 'HK', label: 'Hong Kong', ddi: '+852', flag: '🇭🇰' },
    { code: 'TW', label: 'Taiwan', ddi: '+886', flag: '🇹🇼' },
    { code: 'EG', label: 'Egito', ddi: '+20', flag: '🇪🇬' },
    { code: 'MA', label: 'Marrocos', ddi: '+212', flag: '🇲🇦' },
    { code: 'NG', label: 'Nigéria', ddi: '+234', flag: '🇳🇬' },
    { code: 'KE', label: 'Quênia', ddi: '+254', flag: '🇰🇪' }
];

// Helper to get country by code
export const getCountry = (code) => COUNTRIES.find(c => c.code === code) || COUNTRIES[0];
